baseURL: https://docs.datadoghq.com/
buildfuture: false
builddrafts: false
enableGitInfo: true

# deployment: 

#     targets: 
#     - name: "live"
#       URL: "s3://datadog-docs-live-hugo?region=us-east-1"
#       include: "**.{html,xml,css,js,eot,ttf,woff,woff2}"
#       exclude: "*"
#       cloudFrontDistributionID: E2X18RNS7PRJWD
#     - name: "liveAssets"
#       URL: "s3://origin-static-assets?region=us-east-1&prefix=documentation/"
#       include: "**.{jpg,jpeg,png,gif,mp4,svg,json,ico,zip,pdf,txt,csv}"
#       exclude: "*"
  
#     matchers:
#     - pattern: "^.+\\.(js|css|svg)$"
#       cacheControl: "max-age=31536000, no-transform, public"
#       gzip: true
#     - pattern: "^.+\\.(eot|ttf|woff|woff2|ico)$"
#       cacheControl: "max-age=31536000, no-transform, public"
#       gzip: false
#     - pattern: "^.+\\.(png|jpg|jpeg|gif|mp4|zip|pdf|txt|csv)$"
#       cacheControl: "max-age=31536000, no-transform, public"
#       gzip: false
#     - pattern: "^.+\\.(html|xml|json)$"
#       gzip: true
#       cacheControl: "public, must-revalidate, proxy-revalidate, max-age=0"